# Custom fields
title: "AskClass News"
description: >
  Exploring the intersection between education and technology;
  how innovations in cross-disciplinary learning reorients our
  trajectory toward love and appreciation of life.

acn:
  date_format: "%b %d, %Y"
  short_name: "AC News"
  color:
    theme: "#ffc100"
    bg: "#222"
  url: "https://acn.askclass.com"
  categories:
    - education
  social:
    twitter: "askclass_com"
  logo:
    image: "logo-icon.svg"
    size: 70
    alt_image: "logo.svg"
    alt_size: 200
    sizes: [ 48, 96, 144, 192, 300, 512 ]
  meta:
    apple_icon: "logo-300.png"
    og_image: "logo-square-512.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      edtech,
      education,
      technology,
      learning,
      teaching,
      student,
      educator,
      university,
      icebreaker,
      student engagement,
      participation
  footer:
    - icon: "copyright"
      href: "https://askclass.com"
      text: "AskClass"
    - icon: "toys"
      href: "https://app.askclass.com"
      text: "Icebreakers"
  # Donot change the below (will figure something out later)
  font_families:
    - Teko
    - Open+Sans
    - Josefin+Sans
    - Share+Tech+Mono
    - Material+Icons

collections_dir: content
collections:
  writers:
    output: true
  hashtags:
    output: true

ignore_theme_config: false
excerpt_separator: "<!--more-->"
permalink: /:year/:month/:day/:title

defaults:
  - scope:
      type: "hashtags"
    values:
      layout: "hashtag"
  - scope:
      type: "writers"
    values:
      layout: "writer"
  - scope:
      type: "posts"
    values:
      layout: "post"

sass:
  style: compact

include:
  - index.html
  - 404.html
  - pwabuilder-sw.js
  - content

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - askclass-news-theme.gemspec
  - CNAME
  - runme.sh

