name: Gem Push

on: push

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
         bundler-cache: true

      #- run: bundle exec rake build
      - run: gem build askclass-news-theme.gemspec

      - uses: fac/ruby-gem-setup-credentials-action@v2
        with:
          token: ${{ secrets.RUBYGEMS_TOKEN }}
          key: rubygems

      - uses: fac/ruby-gem-push-action@v2
        with:
          key: rubygems
