name: Gem Push

on: push

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
         bundler-cache: true

      - name: Get Version
        id: version
        run: echo ::set-output name=VER::\
          $(grep 'spec.version' askclass-news-theme.gemspec | cut -d'"' -f2)

      - name: Get Package Name
        id: name
        run: echo ::set-output name=NAME::\
          $(grep 'spec.name' askclass-news-theme.gemspec | cut -d'"' -f2)

      - name: Build
      - run: gem build ${{ steps.version.outputs.NAME }}.gemspec

      - uses: fac/ruby-gem-setup-credentials-action@v2
        with:
          token: ${{ secrets.RUBYGEMS_TOKEN }}
          key: rubygems

      - run:
          gem push --key=rubygems ${{ steps.version.outputs.NAME }}-${{ steps.version.outputs.VER }}.gem
